### ISSUE TITLE
Cant get my auth token

### ISSUE THREAD

**Issue by QRZ-RUNS-YOU** [God-SG/PartyHax#1]
the tool cant get my auth token i keep getting this error when trying to

![image](https://github.com/God-SG/PartyHax/assets/155032954/6bb7b0fd-86d2-497c-8095-1f364462f8e6)

i dont know how to get my token manually either

could u help?

**Comment by BYZIC-DEAD-YOU** [comment]
ich habe das gleiche Problem auch

**Comment by God-SG** [comment]
Just fixed oauth
